package com.prostaff_service_admin_logger.inter_service_communication.enums;

public enum LogType {
	EMPLOYEE_ADDED, 
	EMPLOYEE_DELETED, 
	EMPLOYEE_DETAILS_UPDATED, 
	LEAVE_REQUEST_APPROVED, 
	LEAVE_REQUEST_DENIED, 
	HOLIDAY_ADDED, 
	UPCOMING_EVENT_ADDED, 
	UPCOMING_EVENT_REMOVED, 
	FAQ_ADDED, FAQ_REMOVED, 
	CONTACT_DETAILS_UPDATED, 
	DEPARTMENT_ADDED, 
	DEPARTMENT_REMOVED, 
	DESIGNATION_ADDED, 
	DESIGNATION_REMOVED, 
	TEAM_ADDED, 
	TEAM_REMOVED, 
	NOTIFICATION_ADDED, 
	NOTIFICATION_REMOVED, 
	NOTIFICATION_UPDATED
}
